[[redirects]]
  from = "https://domain1222.netlify.app/*"
  to = "https://1.new.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://2.old.com/*"
  to = "https://2.new.com/:splat"
  status = 301
  force = true
