[[redirects]]
  from = "https://slb.ssangyongsports.ngo.us/*"
  to = "https://slb.sysport.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://2.old.com/*"
  to = "https://2.new.com/:splat"
  status = 301
  force = true
